name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Simple test
        run: |
          echo "Workflow is working!"
          echo "Repository structure:"
          ls -la
          
  build-react:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'react-project/') || github.event_name == 'workflow_dispatch'
    
    defaults:
      run:
        working-directory: react-project/Exp-3.1
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if React project exists
        run: |
          echo "Checking if react project exists..."
          if [ -f "package.json" ]; then
            echo "package.json found!"
            cat package.json
          else
            echo "package.json not found in react-project/Exp-3.1"
            echo "Current directory contents:"
            ls -la
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          if [ -f "package.json" ]; then
            npm ci
            npm run build
          else
            echo "Skipping npm install - no package.json found"
          fi
